# Generated by Django 2.2.6 on 2020-04-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpost',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productpost',
            name='title',
            field=models.CharField(default='Test', max_length=100),
        ),
        migrations.AlterField(
            model_name='productpost',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
