# Generated by Django 2.2.6 on 2020-04-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200408_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpost',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
