# Generated by Django 2.2.6 on 2020-04-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpost',
            name='price',
            field=models.FloatField(default=0.0, max_length=10),
        ),
    ]
