# Generated by Django 2.2.6 on 2020-04-08 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200408_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpost',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='productpost',
            name='title',
        ),
    ]
