# Generated by Django 2.2.6 on 2020-04-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200408_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpost',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productpost',
            name='title',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
