# Generated by Django 2.2.6 on 2020-04-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200408_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpost',
            name='tags',
            field=models.CharField(default='test', max_length=10000),
        ),
    ]
