# Generated by Django 2.2.6 on 2020-04-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200418_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='Address', max_length=10000),
        ),
        migrations.AddField(
            model_name='order',
            name='address_filled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='City', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default='Country', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='Name', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='State', max_length=30),
        ),
    ]
