# Generated by Django 2.2.6 on 2020-04-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productpost_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpost',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
