# Generated by Django 2.2.6 on 2020-04-20 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200419_1434'),
        ('products', '0008_auto_20200420_1607'),
    ]

    operations = [
    ]
