# Generated by Django 2.2.6 on 2020-04-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200412_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpost',
            name='summary',
            field=models.TextField(default='No Summary', max_length=200),
        ),
        migrations.AlterField(
            model_name='productpost',
            name='descrip',
            field=models.TextField(max_length=10000),
        ),
    ]
