# Generated by Django 2.2.6 on 2020-04-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_merge_20200420_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpost',
            name='revenue',
            field=models.FloatField(default=0.0, max_length=10),
        ),
    ]
