# Generated by Django 2.2.6 on 2020-04-14 19:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200412_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpost',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='productpost',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productpost',
            name='sold',
            field=models.IntegerField(default=0),
        ),
    ]
