# Generated by Django 2.2.6 on 2020-04-20 22:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpost',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
