# Generated by Django 2.2.6 on 2020-04-15 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200415_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='productID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductPost'),
        ),
    ]
