# Generated by Django 2.2.6 on 2020-04-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productpost_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpost',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
