# Generated by Django 2.2.6 on 2020-04-15 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200415_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='productID',
            new_name='product',
        ),
    ]
