# Generated by Django 2.2.6 on 2020-04-21 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_productpost_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpost',
            name='timestamp',
        ),
    ]
