# Generated by Django 2.2.6 on 2020-04-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomName', models.TextField()),
                ('username', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
    ]
