# Generated by Django 2.2.6 on 2020-04-20 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_loadmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadmessage',
            name='roomName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
