# Generated by Django 2.2.6 on 2020-04-20 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200420_0216'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoadMessage',
        ),
    ]
