# Generated by Django 2.2.6 on 2020-04-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='roomName',
            field=models.TextField(),
        ),
    ]
