# Generated by Django 2.2.6 on 2020-04-20 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20200420_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.TextField(default='NULL'),
        ),
    ]
